version: '3.7'
services:
  mongodb:
    image: mongo:latest
    networks:
      - framework_network      
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == wk-server
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - /usr/data/mongo:/data/db
networks:
  framework_network:
    external: true
