version: '3.9'
services:
  mysql:
    image: mysql
    networks:
      framework_network:
        aliases:
          - mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      placement:
        constraints:
          - node.hostname == wk-server1
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    configs:
      - source: mysql_config
        target: /etc/mysql/my.cnf
volumes:
  mysql_data:
    driver: local

configs:
  mysql_config:
    external: true

networks:
  framework_network:
    external: true


# 创建config
# docker config create mysql_config ./mysql.cnf


# ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'newpwd';

# 添加远程登录用户
# CREATE USER 'mysql' IDENTIFIED WITH mysql_native_password BY '123456';
# GRANT ALL PRIVILEGES ON *.* TO 'mysql';


# 为从库服务器 设置用户名和密码
# CREATE USER 'slave'@'wk-server' IDENTIFIED BY '123456';
# grant replication slave, replication client on *.* to 'slave'@'wk-server'; --设置权限
# flush privileges;  --权限生效

#找到主节点的同步位置
# show master status;

# 暂停从节点同步
# stop slave;

# 配置主节点信息
#  change master to
#  master_host='wk-server',
#  master_user='slave',
#  master_password='pwd',
#  MASTER_LOG_FILE='binlog.000085',
#  MASTER_LOG_POS=156 ;